#!/bin/bash

accessLog=/tmp/esetAV/accessLog
scanInProgressLog=/tmp/esetAV/scanInProgress

inotifywait -m -e CLOSE_WRITE -r --timefmt "%F %T" --format "%T %w" /mnt/monitor \
        | while read ENTRY
                do
                        FILEDIRECTORY=$(echo $ENTRY | sed 's/.*\s//')
                        REGEX="(\/\w+){3}\/"
                        [[ $FILEDIRECTORY =~ $REGEX ]]
                        ROOTDIRECTORY=$BASH_REMATCH
                        TIMESTAMP=$(echo $ENTRY | sed "s~$FILEDIRECTORY~~")
                        FIXEDENTRY=$TIMESTAMP$ROOTDIRECTORY
                        grep -q $ROOTDIRECTORY $scanInProgressLog || \
                        flock $accessLog -c "grep -q $ROOTDIRECTORY $accessLog && sed -i \"s~.*$ROOTDIRECTORY~$FIXEDENTRY~g\" $accessLog || echo $FIXEDENTRY >> $accessLog"
                done