#!/bin/bash

accessLog=/tmp/esetAV/accessLog
scanInProgressLog=/tmp/esetAV/scanInProgress
threatLog=/var/threatLog


if [[ -f /opt/eset/esets/installed.txt ]]
then
        while read ENTRY
                do
                        FILEDIRECTORY=$(echo $ENTRY | sed 's/.*\s//')
                        TIMESTAMP=$(echo $ENTRY | sed "s~$FILEDIRECTORY~~")
                        TIMESTAMP=$(date -d "$TIMESTAMP 1 minutes" +%s)
                        t=$(date)
                        t=$(date -d "$t" +%s)
                        if [ $t -ge $TIMESTAMP ];
                        then
                                echo $FILEDIRECTORY >> $scanInProgressLog
                                scanResults=$(/opt/eset/esets/sbin/esets_scan $FILEDIRECTORY)
                                flock $accessLog -c "sed -i \"\~.*$FILEDIRECTORY~d\" $accessLog"
                                echo "$scanResults"
                                echo "$scanResults" | grep -z "threat" >> $threatLog
                                sleep 1
                                sed -i "\~.*$FILEDIRECTORY~d" $scanInProgressLog
                        fi
                done < $accessLog
fi