#! /bin/bash

[[ ! -d /tmp/log ]] && \
    mkdir -p /tmp/log/xrdp /tmp/log/xrdp-sesman && \
    chown nobody:nogroup /tmp/log /tmp/log/xrdp /tmp/log/xrdp-sesman

[[ ! -d /tmp/esetAV ]] && \
    mkdir -p /tmp/esetAV/
    touch /tmp/esetAV/accessLog
    touch /tmp/esetAV/scanInProgress

